M48
; DRILL file {KiCad 7.0.5} date Sun Oct 29 18:10:29 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-29T18:10:29+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2400
%
G90
G05
T1
X4.9488Y-3.7309
T2
X4.4039Y-3.9644
X7.1339Y-3.9644
T0
M30
